version: 2
updates:
  - package-ecosystem: 'docker'
    directory: ''
    open-pull-requests-limit: 5
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pip'
    directory: ''
    open-pull-requests-limit: 5
    schedule:
      interval: 'daily'

# Built with ❤ by [Pipeline Foundation](https://pipeline.foundation)
